# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_NAME: Ivan
ADMIN_LAST_NAME: Chyr
ADMIN_MIDDLE_NAME: Andriy
ADMIN_EMAIL: workdevelopui@gmail.com
ADMIN_PASSWORD: changeme
#Student
STUDENT_NAME: Oleg
STUDENT_LAST_NAME: Zaremba
STUDENT_MIDDLE_NAME: Petro
STUDENT_EMAIL: user@inbox.ru
STUDENT_PASSWORD: chanqwer
ROLES: [admin, faculty_admin, student, teacher, guest]

#admin of first faculty
#fa_e-mail: fa@gmail.com
#fa_passwd: Fffffff1

#teacher of first faculty
#teacher_e-mail: te@gmail.com
#teacher_passwd: Ttttttt1

#1 stud of group ПМ-41
#stud_e-mail: s1@gmail.com
#teacher_passwd: Stttttt1

#2 stud of group ПМ-41
#stud_e-mail: s2@gmail.com
#teacher_passwd: Stttttt1

#3 stud of group ПМ-41
#stud_e-mail: s3@gmail.com
#teacher_passwd: Stttttt1

#4 stud of group ПМ-41
#stud_e-mail: s4@gmail.com
#teacher_passwd: Stttttt1

#5 stud of group ПМ-41
#stud_e-mail: s5@gmail.com
#teacher_passwd: Stttttt1

#6 stud of group ПМ-41
#stud_e-mail: s6@gmail.com
#teacher_passwd: Stttttt1