development:
  adapter: postgresql
  encoding: unicode
  database: webui_dev
  pool: 5
  user: webui
  password: webui


test:
  adapter: postgresql
  encoding: unicode
  database: webuis_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: webuis_production
  pool: 5