development:
  adapter: mysql2
  encoding: utf8
  database: webui_dev
  username: 
  password: root


test:
  adapter: mysql2
  encoding: utf8
  database: webui_test
  username: 
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: webui_production
  username: 
  password: