development:
  adapter: mysql2
  encoding: utf8
  database: webui_dev
  username: 
  password: 


test:
  adapter: mysql2
  encoding: utf8
  database: webui_test
  username: 
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: webui_production
  username: 
  password: