development:
  adapter: mysql2
  encoding: utf8
  database: webui_dev
  username: root
  password: 


test:
  adapter: mysql2
  encoding: utf8
  database: webui_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: webui_production
  username: root
  password: