development:
  adapter: mysql2
  encoding: utf8
  database: webui_dev
  username: root
  password: bmwthebest


production:
  adapter: mysql2
  encoding: utf8
  database: webui_production
  username: root
  password: bmwthebest