development:
  adapter: mysql2
  encoding: utf8
  database: webui_dev
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: webui_production
  username: root
  password: bmwthebest
