octopus:
  environments:
    - development
    - production
  development:
    db_2013:
      adapter: mysql2
      encoding: utf8
      database: db_2013
      username: root
      password: 
    db_2012:
      adapter: mysql2
      encoding: utf8
      database: db_2012
      username: root
      password: 
    default:
      adapter: mysql2
      encoding: utf8
      database: webui_dev
      username: root
      password: 

  production:
    