require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgressChangesController do

  # This should return the minimal set of attributes required to create a valid
  # ProgressChange. As you add validations to ProgressChange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "progress" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgressChangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all progress_changes as @progress_changes" do
      progress_change = ProgressChange.create! valid_attributes
      get :index, {}, valid_session
      assigns(:progress_changes).should eq([progress_change])
    end
  end

  describe "GET show" do
    it "assigns the requested progress_change as @progress_change" do
      progress_change = ProgressChange.create! valid_attributes
      get :show, {:id => progress_change.to_param}, valid_session
      assigns(:progress_change).should eq(progress_change)
    end
  end

  describe "GET new" do
    it "assigns a new progress_change as @progress_change" do
      get :new, {}, valid_session
      assigns(:progress_change).should be_a_new(ProgressChange)
    end
  end

  describe "GET edit" do
    it "assigns the requested progress_change as @progress_change" do
      progress_change = ProgressChange.create! valid_attributes
      get :edit, {:id => progress_change.to_param}, valid_session
      assigns(:progress_change).should eq(progress_change)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProgressChange" do
        expect {
          post :create, {:progress_change => valid_attributes}, valid_session
        }.to change(ProgressChange, :count).by(1)
      end

      it "assigns a newly created progress_change as @progress_change" do
        post :create, {:progress_change => valid_attributes}, valid_session
        assigns(:progress_change).should be_a(ProgressChange)
        assigns(:progress_change).should be_persisted
      end

      it "redirects to the created progress_change" do
        post :create, {:progress_change => valid_attributes}, valid_session
        response.should redirect_to(ProgressChange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved progress_change as @progress_change" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressChange.any_instance.stub(:save).and_return(false)
        post :create, {:progress_change => { "progress" => "invalid value" }}, valid_session
        assigns(:progress_change).should be_a_new(ProgressChange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressChange.any_instance.stub(:save).and_return(false)
        post :create, {:progress_change => { "progress" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested progress_change" do
        progress_change = ProgressChange.create! valid_attributes
        # Assuming there are no other progress_changes in the database, this
        # specifies that the ProgressChange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProgressChange.any_instance.should_receive(:update_attributes).with({ "progress" => "1" })
        put :update, {:id => progress_change.to_param, :progress_change => { "progress" => "1" }}, valid_session
      end

      it "assigns the requested progress_change as @progress_change" do
        progress_change = ProgressChange.create! valid_attributes
        put :update, {:id => progress_change.to_param, :progress_change => valid_attributes}, valid_session
        assigns(:progress_change).should eq(progress_change)
      end

      it "redirects to the progress_change" do
        progress_change = ProgressChange.create! valid_attributes
        put :update, {:id => progress_change.to_param, :progress_change => valid_attributes}, valid_session
        response.should redirect_to(progress_change)
      end
    end

    describe "with invalid params" do
      it "assigns the progress_change as @progress_change" do
        progress_change = ProgressChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => progress_change.to_param, :progress_change => { "progress" => "invalid value" }}, valid_session
        assigns(:progress_change).should eq(progress_change)
      end

      it "re-renders the 'edit' template" do
        progress_change = ProgressChange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressChange.any_instance.stub(:save).and_return(false)
        put :update, {:id => progress_change.to_param, :progress_change => { "progress" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested progress_change" do
      progress_change = ProgressChange.create! valid_attributes
      expect {
        delete :destroy, {:id => progress_change.to_param}, valid_session
      }.to change(ProgressChange, :count).by(-1)
    end

    it "redirects to the progress_changes list" do
      progress_change = ProgressChange.create! valid_attributes
      delete :destroy, {:id => progress_change.to_param}, valid_session
      response.should redirect_to(progress_changes_url)
    end
  end

end
