require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TableDictionariesController do

  # This should return the minimal set of attributes required to create a valid
  # TableDictionary. As you add validations to TableDictionary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TableDictionariesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all table_dictionaries as @table_dictionaries" do
      table_dictionary = TableDictionary.create! valid_attributes
      get :index, {}, valid_session
      assigns(:table_dictionaries).should eq([table_dictionary])
    end
  end

  describe "GET show" do
    it "assigns the requested table_dictionary as @table_dictionary" do
      table_dictionary = TableDictionary.create! valid_attributes
      get :show, {:id => table_dictionary.to_param}, valid_session
      assigns(:table_dictionary).should eq(table_dictionary)
    end
  end

  describe "GET new" do
    it "assigns a new table_dictionary as @table_dictionary" do
      get :new, {}, valid_session
      assigns(:table_dictionary).should be_a_new(TableDictionary)
    end
  end

  describe "GET edit" do
    it "assigns the requested table_dictionary as @table_dictionary" do
      table_dictionary = TableDictionary.create! valid_attributes
      get :edit, {:id => table_dictionary.to_param}, valid_session
      assigns(:table_dictionary).should eq(table_dictionary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TableDictionary" do
        expect {
          post :create, {:table_dictionary => valid_attributes}, valid_session
        }.to change(TableDictionary, :count).by(1)
      end

      it "assigns a newly created table_dictionary as @table_dictionary" do
        post :create, {:table_dictionary => valid_attributes}, valid_session
        assigns(:table_dictionary).should be_a(TableDictionary)
        assigns(:table_dictionary).should be_persisted
      end

      it "redirects to the created table_dictionary" do
        post :create, {:table_dictionary => valid_attributes}, valid_session
        response.should redirect_to(TableDictionary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved table_dictionary as @table_dictionary" do
        # Trigger the behavior that occurs when invalid params are submitted
        TableDictionary.any_instance.stub(:save).and_return(false)
        post :create, {:table_dictionary => { "name" => "invalid value" }}, valid_session
        assigns(:table_dictionary).should be_a_new(TableDictionary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TableDictionary.any_instance.stub(:save).and_return(false)
        post :create, {:table_dictionary => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested table_dictionary" do
        table_dictionary = TableDictionary.create! valid_attributes
        # Assuming there are no other table_dictionaries in the database, this
        # specifies that the TableDictionary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TableDictionary.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => table_dictionary.to_param, :table_dictionary => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested table_dictionary as @table_dictionary" do
        table_dictionary = TableDictionary.create! valid_attributes
        put :update, {:id => table_dictionary.to_param, :table_dictionary => valid_attributes}, valid_session
        assigns(:table_dictionary).should eq(table_dictionary)
      end

      it "redirects to the table_dictionary" do
        table_dictionary = TableDictionary.create! valid_attributes
        put :update, {:id => table_dictionary.to_param, :table_dictionary => valid_attributes}, valid_session
        response.should redirect_to(table_dictionary)
      end
    end

    describe "with invalid params" do
      it "assigns the table_dictionary as @table_dictionary" do
        table_dictionary = TableDictionary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TableDictionary.any_instance.stub(:save).and_return(false)
        put :update, {:id => table_dictionary.to_param, :table_dictionary => { "name" => "invalid value" }}, valid_session
        assigns(:table_dictionary).should eq(table_dictionary)
      end

      it "re-renders the 'edit' template" do
        table_dictionary = TableDictionary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TableDictionary.any_instance.stub(:save).and_return(false)
        put :update, {:id => table_dictionary.to_param, :table_dictionary => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested table_dictionary" do
      table_dictionary = TableDictionary.create! valid_attributes
      expect {
        delete :destroy, {:id => table_dictionary.to_param}, valid_session
      }.to change(TableDictionary, :count).by(-1)
    end

    it "redirects to the table_dictionaries list" do
      table_dictionary = TableDictionary.create! valid_attributes
      delete :destroy, {:id => table_dictionary.to_param}, valid_session
      response.should redirect_to(table_dictionaries_url)
    end
  end

end
